kind: Deployment
apiVersion: extensions/v1beta1
metadata:
   name: demodeploy
spec:
   replicas: 2
   template:
     metadata:
       name: testpods
       labels:
         name: qadeploy
     spec:
      containers:
        - name: myimage
          image: raviranjan5937/hello_world:latest
          ports:
          - containerPort: 8080
